### ISSUE TITLE
If description for Gist is too long it will not be able to make directory

### ISSUE THREAD

**Issue by mhenes** [sanusart/gists-backup#3]
Shell-
Error: Error: ENAMETOOLONG: name too long, mkdir

Error occurs when the description is too long for the gist, making the local filesystem unable to make a directory, file, or save the code.

Other code is saved if it comes before the error, script breaks not saving all other code otherwise.

Excellent script, has really made my life easier, but wish I could find a way to work around this error.

**Comment by sanusart** [comment]
Hmm, I am open to suggestions on what to do with it. Should it be trim-ed? It seems that most systems support up to 255 characters in a file name.

**Comment by mhenes** [comment]
@sanusart thank you kindly for the prompt response, I agree with your thoughts, my initial thought also was that the description should be trimmed with an option/flag for that capability to be turned on/off.
Not sure why someone wouldn't want the option "on" though, maybe it would be "on" by default?
Just some thoughts.

Personally though, automatically trimming it would be great for me, 255 characters would work for me, and reminds of MySQL varchar(255) data type/limit.

**Comment by sanusart** [comment]
A more careful read about file systems reveals that cyrillic characters for example, may take 2 bytes per char, thus thus making max file name be 255 / 2 = **127** chars. Need to see how to better approach this issue. Thank you for heads-up @mhenes.

**Comment by mhenes** [comment]
@sanusart that makes perfect sense, hadn't considered the 2 bytes per char; thank you again for everything.  If I can help in any way, please let me know and I'll be glad to contribute.

**Comment by mhenes** [comment]
@sanusart any update on this? I value this module and your work a lot. 

Best Regards.

**Comment by sanusart** [comment]
@mhenes Sorry. Too much on my mind lately. Long descriptions should be fine.

**Comment by mhenes** [comment]
@sanusart completely understand, you are the best; thank you kindly!
