### ISSUE TITLE
Doesn't seem to work for me.

### ISSUE THREAD

**Issue by sjs7007** [sanusart/gists-backup#4]
Typing in gist-backup does nothing for me.

**Comment by sanusart** [comment]
Not even errors?

**Comment by sjs7007** [comment]
Not even errors. I have created a [recording](http://showterm.io/29d5d38c6ee7778eb5427) of it.

**Comment by sanusart** [comment]
And if you run it directly by 

``` bash
/usr/local/bin/gist-backup
```

?

**Comment by sjs7007** [comment]
Same. That's not the issue because if it was not added to the path, it would have returned something like gist-backup command not found.

**Comment by sanusart** [comment]
Hmm. Can you hint on your setup, nodejs version, is, etc...

**Comment by sjs7007** [comment]
OS : Ubuntu 14.04
Node.js version : 0.10.25

**Comment by sanusart** [comment]
Cool. I'll test in this environment and get back to you.

**Comment by sanusart** [comment]
It worked for me (on ubuntu 14.04 virtual machine).
Maybe you could try to run the script directly with:
`node /usr/local/lib/node_modules/gist-backup/gist-backup.js`
or 
`nodejs /usr/local/lib/node_modules/gist-backup/gist-backup.js`

Because I am getting out of ideas :(

**Comment by sjs7007** [comment]
> nodejs /usr/local/lib/node_modules/gist-backup/gist-backup.js

This did the trick!

**Comment by sanusart** [comment]
OK. So this is some issue with how ubuntu treads nodejs installation I
guess.
