### ISSUE TITLE
Special chars in description

### ISSUE THREAD

**Issue by majkinetor** [sanusart/gists-backup#5]
Currently gist-backup removes `#` char which is used on [gistlist](https://gistlist.ksdev.pl) to specify tags for the gist. Could you fix it so that local copy retains it ? Only non valid file system chars should be removed.

**Comment by majkinetor** [comment]
Thanks. :+1: 
When will this be available via npm ?

**Comment by sanusart** [comment]
@majkinetor It is now. Sorry, forgot.
